title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
workshop:
  name: 2nd Workshop on Novel Benchmarks and Approaches for Real-World Continual Learning
  short: CL4REAL
  host: "ICIAP 2023\nUdine, Italy\nSeptember 11-15, 2023"
  dates:
    submission: June 30, 2023
    decision: July 30, 2023
    camera_ready: August 15, 2023
    workshop: September 11-15, 2023 (TBD)
